ALTER TABLE users
  ADD COLUMN IF NOT EXISTS cellphone VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS failed_attempts INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_cellphone ON users((cellphone)) WHERE cellphone IS NOT NULL;